# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-15 13:33
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_named_menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmsnamedmenu',
            options={'verbose_name': 'CMS Menu', 'verbose_name_plural': 'CMS Menus'},
        ),
        migrations.AlterField(
            model_name='cmsnamedmenu',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
    ]
